version: "3.5"

services:
  api01: &api
    image: rinha-backend-2024-q1:latest
    hostname: api01
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/minha-rinha
    ports:
      - 8081:8080
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    volumes:
      - ./target/MinhaRinha-0.0.1-SNAPSHOT.jar:/minha-rinha.jar
  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/minha-rinha
    ports:
      - "8082:8080"
  db:
    image: mysql:latest
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=a1b9c2d8.
      - MYSQL_DATABASE=minha-rinha
#    ports:
#      - "3306:3306"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.13"
#          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
#networks:
#  default:
#    driver: bridge
#    name: rinha-nginx-2024q1