version: "3.5"

services:
  api01:
    image: rinha-backend-2024-q1:latest
    hostname: api01
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/minha-rinha
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    volumes:
      - ./target/MinhaRinha-0.0.1-SNAPSHOT.jar:/minha-rinha.jar
  db:
    image: mysql:latest
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=a1b9c2d8.
      - MYSQL_DATABASE=minha-rinha
#    ports:
#      - "3306:3306"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.13"
#          memory: "140MB"
#networks:
#  default:
#    driver: bridge
#    name: rinha-nginx-2024q1